/**
 * ESP32 secrets file
 * 
 * Contains information required to connect to WiFi and in-turn, AWS IoT
 * 
 * Authors: Vipul Deshpande, Jaime Burbano
 */


/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


#include <pgmspace.h>

#define SECRET
#define THINGNAME "Tank8964"

const char WIFI_SSID[] = "eduroam";
const char EAP_ANONYMOUS_IDENTITY[] = "eduroam@fh-dortmund.de";
const char EAP_IDENTITY[] = "mang001";
// const char EAP_PASSWORD[] = "no, this is not my real password";

const char AWS_IOT_ENDPOINT[] = "a5snnrsfqks2n-ats.iot.eu-central-1.amazonaws.com";

/* Amazon Root CA 1 */
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

/* Device Certificate */
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUHSOfhPCvJa5za8tNFlu5MjFfRb0wDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIyMTIwMzEzNTIx
OVoXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKfHPbBvqZZGoXN2F0LJ
vP6jxG0G/CH0rifol5Y6UUuqAfX14cuWr3a+hboo2Y8eUfP5DaY81EnB4nF3x4lN
GNfaKKJ4sTlMZgLX0vRVFnDs0nscIOUxNosWgQYRQ/ie4NrufdhfbEe6w8CIvTpi
wfEw9ZJxMBA2Mj8REaO0Pu3PeOhr3EaS/lkTs/WGpSJh4E/fplKAYGCylArR99ve
Zy0BKE0fdCsfRwdo5pqrGD2ht/Huoju0f5ZCtCx+iM7IT7hvXPMv0upy4ebIQCiA
i5b1Ltqc0tWWCA+x9TQ8hj/KYl5OfKlNvTvosDAKx2d6sGOhKsyijT2s+iyg1Nfw
Xi8CAwEAAaNgMF4wHwYDVR0jBBgwFoAUTXdhta1V4VCoxKA/La2thEkGTaYwHQYD
VR0OBBYEFI3yuz9id3FLZkHi7OvANGJg16YHMAwGA1UdEwEB/wQCMAAwDgYDVR0P
AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQAHwMXEV5+HwNbfyL4mlI+Oe3JC
8++LKw/GOSAq6GpH9OoCXAW2Sxb/AkKbPeid6/AzgZs6EYlPsCe/C+Jl+1KTQWtQ
TiL1kzO4jCpp1E4NoZ3Fx1Qau4aUe/zVsHOdOpe7EE9nMTz3MPb1dGP9B/Y115oW
wumMofzHjFYUCFt7v0I5c2EnhGZsGdKSiEy01T4+k1q+TmFjpUod76TirR/Xcywr
Y5vIZ8JarE2+OqbPw/5/PTnTqLXz1bQQvFdUBThOB/82et+06mcun7PyTJgbn+iB
m8GepvcXIbIO0HwXqrcvdKyHjfrlp4unJYCMQ9Rew303pEOl2Jwun9GCOmwn
-----END CERTIFICATE-----
)KEY";

/* Device Private Key */
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAp8c9sG+plkahc3YXQsm8/qPEbQb8IfSuJ+iXljpRS6oB9fXh
y5avdr6FuijZjx5R8/kNpjzUScHicXfHiU0Y19ooonixOUxmAtfS9FUWcOzSexwg
5TE2ixaBBhFD+J7g2u592F9sR7rDwIi9OmLB8TD1knEwEDYyPxERo7Q+7c946Gvc
RpL+WROz9YalImHgT9+mUoBgYLKUCtH3295nLQEoTR90Kx9HB2jmmqsYPaG38e6i
O7R/lkK0LH6IzshPuG9c8y/S6nLh5shAKICLlvUu2pzS1ZYID7H1NDyGP8piXk58
qU29O+iwMArHZ3qwY6EqzKKNPaz6LKDU1/BeLwIDAQABAoIBAAToWhCYI5DGviA/
ewy0E/gq2CsMQkHIA3QdZJm7WPdqoKYOLC2lWbqSdhzs5vg9vc3yIgkTzG3f4vzI
sSh9/dUKh5fBCgYQCwfYQk5tUru44atCNmAd4WeOH/YKeT+DfjZJNZsnp2Ytu14d
YdOcYenpMbW3490FiNC5chekxRZ1qAapZHWl03ryx9HONeuY9erpIhiLYmT9z5ov
gRSt3lH/WkR91bPgSgxpniycmg2EuAF53fwctXVivIGMsNvE1gumy5ejyABCayWC
uH8g2LE5AOxbySVM6dDGzAB7/vo/m0I9N+c7uglASOHb69pPpTKmjBpUWFFFeh40
oi7BK0kCgYEA0cg+/QHKGj/oEUQaFyEkqIlQLJfn3oCzn6wOpEiytUzl+sSg3JA/
mwsSKkHMJbDiNux9IoQFmjA1dk5bq9hmfN859AFvmOJpFbeR3CPv4ryNrAP2DqKM
kr6rC8hE6ll115ZkXfck53zvFeOZAr8SgKLBhRM24ODu8Q2z5XPpwpUCgYEAzL33
TjyZu8x7hk3MNRdsShaLmhbPIlefQlvxw3VlySEvTqwi9NsbxpmyIjWDHYjFteC8
fOp4VbHgpzG1CYEKHH+fixKvlPfS240cNyr6t0Q10GDF0HlFq5Ny+hOyPS+RGjnD
G0wMnyFaRPIyPZ2oN/5WQ/zu29InNvfUtlEEELMCgYAX10IRTtrBEPI2xB6S8llQ
LgrGhpz7VHUVeGBRm1Fz+UFJtn7xkhMoc6Gk28VvoyKSS14NRiO82i25PD5+0SEU
n+neKSudnF2E8k/JTOw+QF95ZRnZn++J3dFijWgHmhMiZR0S8Lto83HYcv04qq5X
oCeOEBj0hZuiGYSQVxQB4QKBgQDC+4LiykmqFNHqlHqOcTEa2Z+3blNzJDkyTDfQ
6iO2SNkxtjNQNr6cA1EmzQmB/fgz/sPivrU8/zqwX2FGnNJRU6VQH8qBNwZjOl6N
l2vPTrFlMlQQ9v1HqhOMX2eWZ49rh2jsvR8kCPJbyL/Z+CP0t03WT7H2PIxGB/1W
Z49UiwKBgAL2OOSH9yr4bKFAxv3wEu5D4w/KHqzq1J1/EGIdTTPkNcfD7mV3/HDP
Rf/CWH2DF4Lyf6hSaEQ1qpfbB/SfpnuDmQr4x8GBnUuflGFQTNilnWo1CByiC3s5
JB3x6A4kLoVgcS0knBpPJ9zrz6+HV8sppOePfOLbhOypngidDF5P
-----END RSA PRIVATE KEY-----
)KEY";